### ISSUE TITLE
Error	CS0103	The name 'JsonConvert' does not exist in the current context	130	Active

### ISSUE THREAD

**Issue by Kayumiy** [InsaneQA/UnityMedievalCityImporter#2] opened 2021-02-10 08:46 UTC
![image](https://user-images.githubusercontent.com/22438366/107485841-225a0480-6ba6-11eb-8228-e4e1c510eda8.png)
![image](https://user-images.githubusercontent.com/22438366/107485902-37cf2e80-6ba6-11eb-8ae2-443a6d83bf0c.png)

**Comment by InsaneQA** [comment] 2021-02-11 07:19
Hi @Kayumiy,
the project requires the newtonsoft package for json, it can be found here - https://www.newtonsoft.com/json
Just unpack the .dll somewhere in the Assets folder, and you are ready to go.
If the error persists, please let me know.

**Comment by InsaneQA** [comment] 2021-02-12 09:41
I'm closing the issue. Please let me know if the issue is reproducible again

**Closed as completed by InsaneQA** 2021-02-12 09:41 UTC
Labels: wontfix
